apiVersion: v1
kind: Service
metadata:
  labels:
    app: prerender
  name: prerender
  namespace: prerender
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: prerender
  type: ClusterIP