name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: k14s/setup-k14s-action@v1
      with:
        only: kapp    
    - name: dry-run
      if: github.ref != 'refs/heads/master'
      run: |
        set -ex
        export PATH=${PATH}:/tmp
        ./deploy-prerender.sh --diff-run       
    - name: deploy-to-k8s
      if: github.ref == 'refs/heads/master'
      run: |
        set -ex
        export PATH=${PATH}:/tmp
        ./deploy-prerender.sh -y
