name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - name: install-kapp
      run: |
        set -ex
        wget -O kapp https://github.com/k14s/kapp/releases/download/v0.31.0/kapp-linux-amd64
        install kapp /tmp/         
    - name: dry-run
      run: |
        set -ex
        export PATH=${PATH}:/tmp
        find /home/runner/work
        /home/runner/work/deploy-prerender.sh --diff-run       
    - name: deploy-to-k8s
      if: github.ref == 'refs/heads/master'
      run: |
        set -ex
        export PATH=${PATH}:/tmp
        /home/runner/work/deploy-prerender.sh -y